TallerChaPin/TallerChaPin/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from TallerChaPin.views import *
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('', home, name="home"),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('taller/', include('taller.urls')),
    path('ordenes/', include('ordenes.urls')),
    path('facturas/', include('facturas.urls')),
    path('reportes/', include ('reportes.urls')),
    path('taller/', template_taller, name='taller_home'),
    path('ordenes/', template_ordenes, name='ordenes_home'),
    path('facturas/', template_facturas, name='facturas_home'),
    path('listados/', template_listados, name='listados_home'),
    path('reportes/', template_reportes, name='reportes_home'),
    path('admin/', admin.site.urls),
    re_path(r'^docs/', include('docs.urls')),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
]

TallerChaPin/taller/urls.py
from django.urls import path
from .views import *


urlpatterns = [

     path('materiales/unidades_de_medida/<int:pk>', UnidadesDeMedida),
     path('cliente/vehiculos/<int:pk>', vehiculosDelCliente),
     # ----------------- MARCAS -----------------

     path('marcas/crear', MarcaCreateView.as_view(), name="crearMarca"),
     path('marcas/listar', MarcaListView.as_view(), name="listarMarcas"),
     path('marca/modificar/<int:pk>',
          MarcaUpdateView.as_view(), name="modificarMarca"),
     path('marca/eliminar/<int:pk>',
          MarcaDeleteView.as_view(), name="eliminarMarca"),
     path('marcas/exportar',
          exportar_listado_marcas, name='exportarMarcas'),
     # ----------------- TAREAS -----------------

     path('tarea/crear', TareaCreateView.as_view(), name="crearTarea"),
     path('tarea/modificar/<int:pk>',
          TareaUpdateView.as_view(), name="modificarTarea"),
     path('tarea/eliminar/<int:pk>',
          TareaDeleteView.as_view(), name="eliminarTarea"),
     path('tareas/listar', TareaListView.as_view(), name="listarTareas"),
     path('tareas/exportar',
          exportar_listado_tareas, name='exportarTareas'),

     # ----------------- TIPOS TAREA -----------------

     path('tipo-tarea/crear', TipoTareaCreateView.as_view(), name="crearTipoTarea"),
     path('tipo-tarea/modificar/<int:pk>',
          TipoTareaUpdateView.as_view(), name="modificarTipoTarea"),
     path('tipo-tarea/eliminar/<int:pk>',
          TipoTareaDeleteView.as_view(), name="eliminarTipoTarea"),
     path('tipo-tarea/listar', TipoTareaListView.as_view(), name="listarTipoTarea"),
     path('tipo-tarea/exportar',
          exportar_listado_tipotareas, name='exportarTipoTareas'),
     # ----------------- REPUESTOS -----------------

     path('repuesto/crear', RepuestoCreateView.as_view(), name="crearRepuesto"),
     path('repuestos/listar', RepuestoListView.as_view(), name="listarRepuestos"),
     path('repuesto/modificar/<int:pk>',
          RepuestoUpdateView.as_view(), name="modificarRepuesto"),
     path('repuesto/eliminar/<int:pk>',
          RepuestoDeleteView.as_view(), name="eliminarRepuesto"),
     path('repuestos/exportar',
          exportar_listado_repuestos, name='exportarRepuestos'),
     # ----------------- MODELO -----------------

     path('modelo/crear', ModeloCreateView.as_view(), name="crearModelo"),
     path('modelos/listar', ModeloListView.as_view(), name="listarModelos"),
     path('modelo/modificar/<int:pk>',
          ModeloUpdateView.as_view(), name="modificarModelo"),
     path('modelo/eliminar/<int:pk>',
          ModeloDeleteView.as_view(), name="eliminarModelo"),
     path('modelos/exportar',
          exportar_listado_modelos, name='exportarModelos'),
     # ----------------- MATERIALES -----------------

     path('materiales/listar', MaterialListView.as_view(), name="listarMateriales"),
     path('materiales/crear', MaterialCreateView.as_view(), name="crearMaterial"),
     path('materiales/eliminar/<int:pk>',
          MaterialDeleteView.as_view(), name="eliminarMaterial"),
     path('materiales/modificar/<int:pk>',
          MaterialUpdateView.as_view(), name="modificarMaterial"),
     path('materiales/modificarCantidad',
          MaterialCantidad, name="modificarCantidad"),
     path('materiales/exportar',
          exportar_listado_materiales, name='exportarMateriales'),
     # ----------------- TIPOS MATERIALES -----------------

     path('tipos-materiales/crear', 
          TipoMaterialCreateView.as_view(), name="crearTipoMaterial"),
     path('tipos-materiales/listar', 
          TipoMaterialListView.as_view(), name="listarTipoMateriales"),
     path('tipos-materiales/modificar/<int:pk>',
          TipoMaterialUpdateView .as_view(), name="modificarTipoMaterial"),
     path('tipos-materiales/eliminar/<int:pk>',
          TipoMaterialDeleteView.as_view(), name="eliminarTipoMaterial"),
     path('tipo-materiales/exportar',
          exportar_listado_tipomateriales, name='exportarTipoMateriales'),
     # ----------------- CLIENTES -----------------

     path('clientes/listar', 
          ClienteListView.as_view(), name='listarClientes'),
     path('clientes/crear', 
          ClienteCreateView.as_view(), name='crearCliente'),
     path('clientes/modificar/<int:pk>',
          ClienteUpdateView .as_view(), name="modificarCliente"),
     path('clientes/eliminar/<int:pk>',
          ClienteDeleteView.as_view(), name="eliminarCliente"),
     path('clientes/exportar',
          exportar_listado_clientes, name='exportarClientes'),
     # ----------------- VEHÍCULOS -----------------

     path('vehiculos/listar', 
          VehiculoListView.as_view(), name="listarVehiculos"),
     path('vehiculos/crear', 
          VehiculoCreateView.as_view(), name="crearVehiculo"),
     path('vehiculos/modificar/<int:pk>',
          VehiculoUpdateView.as_view(), name="modificarVehiculo"),
     path('vehiculos/eliminar/<int:pk>',
          VehiculoDeleteView.as_view(), name="eliminarVehiculo"),
     path('vehiculos/exportar',
          exportar_listado_vehiculos, name='exportarVehiculos'),
     # ----------------- EMPLEADOS -----------------

     # path('empleado/registro_usuario/<int:pk>',
     #      RegistrarUsuarioCreateView.as_view(), name="registroEmpleado"),
     path('empleado/imprimir_pdf/<int:pk>',
          imprimirUsuarioEmpleado.as_view(), name="usuarioPDF"),
     path('empleado/registrar',
          EmpleadoCreateView.as_view(), name="crearEmpleado"),
     path('empleado/modificar/<int:pk>',
          EmpleadoUpdateView.as_view(), name="modificarEmpleado"),
     path('empleado/eliminar/<int:pk>',
          EmpleadoDeleteView.as_view(), name="eliminarEmpleado"),
     path('empleados/listar', 
          EmpleadoListView.as_view(), name="listarEmpleados"),
     path('empleados/exportar',
          exportar_listado_empleados, name='exportarEmpleados'),
     path('empleado/asociar_tarea/<int:pk>',
          asociar_tarea_empleado, name='asociarTarea'),
]

TallerChaPin/taller/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.core.exceptions import ValidationError
from datetime import date
from django.core.validators import MinValueValidator

# Create your models here.
# http://....../?atributo__contains=valor
# FILTRO = {'atributo__contains': valor}
# ...?nombre__icontains=a&marca__exact=1


def validacion_nombre_unico(modelo, campo, value):
    aux = dict([(f"{campo}__iregex", f'^{value}$')])
    if modelo.objects.filter(**aux).exists():
        raise ValidationError({"nombre": "nombre ya existe"}) #TODO: se muestran con un formato malo
    # return validateeven


def texto_to_query(texto):
    filtros = dict([chunk.split("=") for chunk in texto.split("&")])
    filtro = models.Q()
    for attr, value in filtros.items():
        if value.isdigit():
            value = int(value)
        filtro &= models.Q(**{attr: value})
    return filtro


class MarcaQuerySet(models.QuerySet):
    def filtrar(self, texto):
        return self.filter(texto_to_query(texto))


class Marca(models.Model):
    nombre = models.CharField(max_length=50, unique=True)
    descripcion = models.CharField(max_length=200, blank=True)
    objects = MarcaQuerySet.as_manager()

    def __str__(self):
        return self.nombre

    def clean(self) -> None:
        validacion_nombre_unico(Marca, "nombre", self.nombre)
        return super().clean()


class ModeloQuerySet(models.QuerySet):
    def filtrar(self, texto):
        return self.filter(texto_to_query(texto))

def anio_valido(anio):
    if anio > date.today().year:
        raise ValidationError('El año del modelo no puede ser mayor al año actual')
class Modelo(models.Model):
    nombre = models.CharField(max_length=50, unique=True)
    descripcion = models.CharField(max_length=200, blank=True)
    marca = models.ForeignKey(
        Marca, related_name="modelos", on_delete=models.RESTRICT)
    anio = models.PositiveSmallIntegerField(validators=[anio_valido])

    # Manager de la clase Modelo
    objects = ModeloQuerySet.as_manager()

    def __str__(self):
        return f"{self.nombre}, {self.marca}"

    def clean(self) -> None:
        validacion_nombre_unico(Modelo, "nombre", self.nombre)
        return super().clean()


class TipoTarea(models.Model):
    nombre = models.CharField(max_length=50, unique=True)
    descripcion = models.CharField(max_length=200, blank=True)
    # Requiere Material[si/no]
    materiales = models.BooleanField(default=False)
    # Requiere Repuesto[si/no]
    repuestos = models.BooleanField(default=False)
    # Requiere Planilla[si/no]
    planilla = models.BooleanField(default=False)

    def __str__(self):
        return self.nombre

    def clean(self) -> None:
        validacion_nombre_unico(TipoTarea, "nombre", self.nombre)
        return super().clean()

    def get_req_materiales(self):
        return self.materiales
    
    def get_req_repuestos(self):
        return self.repuestos
    
    def get_req_planilla(self):
        return self.planilla

class Tarea(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=200, blank=True)
    tipo = models.ForeignKey(TipoTarea, on_delete=models.RESTRICT)
    precio = models.DecimalField(max_digits=10, decimal_places=2, validators = [MinValueValidator(0)])

    def __str__(self):
        return self.nombre

    def eliminable(self, presupuesto_id):
        presupuestos = self.presupuestos.filter(pk=presupuesto_id)
        if presupuestos.exists():
            presupuesto = presupuestos.first()
            if presupuesto.orden:
                detalles = presupuesto.orden.detalles.filter(tarea=self)
                return not (detalles.exists() and detalles.first().exitosa)
        return True

class Repuesto(models.Model):
    TIPOS = (
        (1, 'Puerta'),
        (2, 'Guardabarros'),
        (3, 'Parabrisa'),
        (4, 'Cristal'),
        (5, 'Bateria'),
        (6, 'Rueda'),
        (7, 'Mecanico'),
        (8, 'Llanta'),
        (9, 'Suspension'),
        (10, 'Aire Acondicionado'),
        (99, 'Otro'),
    )
    nombre = models.CharField(max_length=50)
    modelo = models.ForeignKey(Modelo, on_delete=models.RESTRICT)
    tipo = models.PositiveSmallIntegerField(choices=TIPOS)
    cantidad = models.IntegerField(blank=True, null=True, default=0, validators = [MinValueValidator(0)])
    precio = models.DecimalField(max_digits=10, decimal_places=2, blank=True, validators = [MinValueValidator(0)])

    def __str__(self):
        return f"{self.nombre}, {self.modelo}"

    def get_tipo(self):
        return self.get_tipo_display()
    
    def decrementar_stock(self,cantidad):
        self.cantidad -= cantidad
        self.save()

class TipoMaterial(models.Model):
    GRAMO = 1
    CM3 = 2
    LITRO = 3
    UNIDAD = 4
    KG = 5
    METRO = 6
    METRO2 = 7
    UNIDADES_BASICAS = (
        (GRAMO, "g"),
        (CM3, "CM3"),
        (UNIDAD, "Unidad/es"),  # Por unidad
        (METRO, "Metro/s"),
        (METRO2, "Metro2")
    )
    # Ejemplos: Remaches, Lijas, Fibra, Resina, Pintura, Masilla, Cinta
    nombre = models.CharField(max_length=50, unique=True)
    unidad_medida = models.PositiveSmallIntegerField(choices=UNIDADES_BASICAS)

    def __str__(self):
        return self.nombre

    # def clean(self) -> None:
    #     validacion_nombre_unico(TipoMaterial, "nombre", self.nombre)
    #     return super().clean()
    def get_unidad_medida(self):
        return self.get_unidad_medida_display()


class Material(models.Model):
    nombre = models.CharField(max_length=50)
    tipo = models.ForeignKey(TipoMaterial, on_delete=models.RESTRICT)
    cantidad = models.IntegerField(blank=True, null=True, default=0)
    precio = models.DecimalField(max_digits=10, decimal_places=2, blank=True, validators = [MinValueValidator(0)])

    def __str__(self):
        return f"{self.nombre} ({self.tipo}) {self.tipo.get_unidad_medida_display()}"

    def decrementar_stock(self, cantidad):
        self.cantidad -= cantidad
        self.save()

    def stock(self):
        return self.cantidad

    def calcular_precio(self, cantidad):
        return self.precio * cantidad


class Cliente(models.Model):
    dni = models.CharField(max_length=8, unique=True)
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    direccion = models.CharField(max_length=100)
    telefono = models.CharField(max_length=50)
    
    def __str__(self):
        return f'{self.nombre} {self.apellido} ({self.dni})'
        
    def get_nombre_abreviado(self):
        return f'{self.nombre[0]}. {self.apellido}'

    def vip(self):
        # Obtener ultimas tres facturas pagas del cliente
        # Ir a los presupuestos
        # Tomar un presupuesto
        # si ese presupuesto tiene una orden, esta confirmado
        # Si la orden tiene una factura, esta facturada
        # ver si las ultimas 3 facturas
        # si hay 3 facturas pagadas es vip, caso contrario no es vip 
        facturas = []
        for presupuesto in self.presupuestos.all():   
            if (presupuesto.orden) != None and (presupuesto.orden.factura) != None:              
                    facturas.extend(presupuesto.orden.factura.all())
            else:
                return False  
        # Veo las ultimas 4, puede adeudar al menos una al ser VIP
        facturas = sorted(facturas, key=lambda f: f.fecha , reverse=True)[:4]
        if len(facturas) >= 4 and not facturas[0].pagado():
            facturas.pop(0) #De estar la mas reciente impaga la quita del listado. VER ESTO 
        return len(facturas) >= 3 and all(f.pagado() for f in facturas) 

def validar_anio(anio):
    if anio < date.today().year - 12:
        raise ValidationError('El vehículo tiene más de 12 años de antigüedad')
    if anio > date.today().year:
        raise ValidationError('El año del vehículo no puede ser mayor al año actual')

class Vehiculo(models.Model):
    cliente = models.ForeignKey(
        Cliente, related_name="vehiculos", on_delete=models.RESTRICT)
    patente = models.CharField(max_length=7, unique=True)
    modelo = models.ForeignKey(Modelo, on_delete=models.RESTRICT)
    anio = models.IntegerField(validators=[validar_anio])
    chasis = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.modelo} - {self.patente}"


class Empleado(models.Model):
    cuil = models.CharField(max_length=13, unique=True)
    legajo = models.IntegerField(null=False)
    nombre = models.CharField(max_length=100, null=False, blank=False)
    apellido = models.CharField(max_length=100, null=False, blank=False)
    tareas = models.ManyToManyField(TipoTarea, related_name="empleados")
    usuario = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)

    def crear_usuario(self):
        base_username = (self.nombre[0] + self.apellido).lower()
        cantidad = User.objects.filter(username__startswith=base_username).count()
        if cantidad == 0:
            username = f"{base_username}"
        else:
            username = f"{base_username}{cantidad}"

        user = User.objects.create_user(
            username=username, password=self.cuil, first_name=self.nombre, last_name=self.apellido)
 
        self.usuario = user
        self.save()
        return user

     
    def añadir_grupos(self, grupos):
        if grupos:
            grupos_obj = [Group.objects.get(name=g) for g in grupos]
            self.usuario.groups.add(*grupos_obj)
            self.usuario.save()
            

    def get_tareas(self):
        tareas = self.tareas.all()
        return ' | '.join([t.nombre for t in tareas]) if tareas is not None else None
    
    def get_grupos(self):
        grupos = Group.objects.filter(user = self.usuario)
        return ', '.join([g.name for g in grupos]) if grupos is not None else None

    def es_admin(self):
        return self.usuario.groups.filter(name='Administrativo').exists()
    

TallerChaPin/taller/templates/taller/cliente_form.html
{% extends 'template_taller.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block main %}
<div class="col-5">
    <h3>{{ titulo }}</h3>
    {% crispy form form.helper %}

</div>
{% endblock %}

TallerChaPin/taller/templates/taller/empleado_list.html
{% extends 'template_taller.html' %}
{% load static %} 
{% load crispy_forms_tags %}
{% block title %} 
{{titulo}} 
{% endblock %} 
{% block main %}
<h1>{{titulo}}</h1>

<div class="table-responsive">
  <table class="table table-hover {% if filtros %} sortable{% endif %}">
    <thead>
      <tr>
        {% for sortable in filtros.sortables %}
          <th class="sortable bg-transition pointer" scope="col" data-s-field={{sortable.0}}>{{sortable.1}}</th>
        {% endfor %}
        <th scope="col">Grupos</th>
        <th scope="col">Tareas que realiza</th>
        <th scope="col">Opciones</th>
      </tr>
    </thead>
    <tbody>
      {% for empleado in object_list %}
      <tr class="bg-transition">
        <td>{{ empleado.nombre }}</td>
        <td>{{ empleado.apellido }}</td> 
        <td>{{ empleado.legajo}}</td>
        <td>{{ empleado.cuil }}</td>
        <td>{{ empleado.get_grupos }}</td>
        <td>{{ empleado.get_tareas }}</td>
        <td>
          {% if perms.taller.change_empleado %}
          <a href="{% url 'modificarEmpleado' empleado.pk %}" class= "btn-modificar btn-listado">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
              <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"></path>
              <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"></path>
            </svg>
          </svg></a>
          {% if not empleado.es_admin %}
          <a href="{% url 'asociarTarea' empleado.pk %}" class= "btn-tareas btn-listado">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 512 512">
              <path
                d="M352 320c88.4 0 160-71.6 160-160c0-15.3-2.2-30.1-6.2-44.2c-3.1-10.8-16.4-13.2-24.3-5.3l-76.8 76.8c-3 3-7.1 4.7-11.3 4.7H336c-8.8 0-16-7.2-16-16V118.6c0-4.2 1.7-8.3 4.7-11.3l76.8-76.8c7.9-7.9 5.4-21.2-5.3-24.3C382.1 2.2 367.3 0 352 0C263.6 0 192 71.6 192 160c0 19.1 3.4 37.5 9.5 54.5L19.9 396.1C7.2 408.8 0 426.1 0 444.1C0 481.6 30.4 512 67.9 512c18 0 35.3-7.2 48-19.9L297.5 310.5c17 6.2 35.4 9.5 54.5 9.5zM80 456c-13.3 0-24-10.7-24-24s10.7-24 24-24s24 10.7 24 24s-10.7 24-24 24z" />
            </svg>
          {% endif %}

          <a href="{% url 'usuarioPDF' empleado.pk %}" class="btn-registrar btn-listado" id="liveAlertBtn2">
          <i class="fa-solid fa-user"  data-toggle="tooltip" data-placement="top" title="Datos de usuario" ></i> </a>


          {% endif %}
          {% if perms.taller.delete_empleado %}
          <a 
            href="#" 
            data-bs-toggle="modal" 
            data-bs-target="#modalEliminarEmpleado"
            data-bs-nombre="{{empleado.nombre}} {{empleado.apellido}}" 
            data-bs-url="{% url 'eliminarEmpleado' empleado.pk %}" 
            class="btn-eliminar btn-listado">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
              <path 
              d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z">
            </path>
          </svg></a>
          {% endif %}
        </td> 
      </tr>
      {% empty %}
      <tr>
        <td>No hay empleados</td>
        <td>n/a</td>
        <td>n/a</td>
        <td>n/a</td>
        <td>n/a</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<div class="col-12 d-flex flex-row-reverse mb-4">
  <a href="{% url 'exportarEmpleados'  %}?{{ request.GET.urlencode }}
    "type="submit" class="btn btn-primary mt-3" data-toggle="tooltip" data-placement="top" title="Exporta el listado a CSV">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download"
      viewBox="0 0 16 16">
      <path
        d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z" />
      <path
        d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z" />
    </svg>
    Descargar listado</a>
</div>


{% endblock %}

{% block filtros%}
  <div>
    {% crispy filtros filtros.helper %}
  </div>
{% endblock %}

{% block modals %} 
{% include './empleado_confirm_delete.html' with idModal='modalEliminarEmpleado' %}
{% comment %} {% include './registro_empleado_form.html' with idModal='modalRegistrarUsuario' form=registroEmpleadoForm %} {% endcomment %}
{% endblock %}

{% block extrajs %} 
<script>
  conectarBotonesAModal('.btn-eliminar', 'modalEliminarEmpleado');
  conectarBotonesAModal('.btn-registrar', 'modalRegistrarUsuario');
</script>
{% endblock %}

TallerChaPin/taller/templates/taller/form_registrar_modelo.html
{% extends 'main.html' %}
{% load static %}

{% block title %} {{titulo}} {% endblock %}

{% block main %}

    <form class="row g-3">
        <h1 class="mt-4">Registrar un Modelo</h1>
        <hr>
        <div class="col-md-6">
            <label for="inputNombre" class="form-label">Nombre</label>
            <input type="text" class="form-control" id="inputNombre">
        </div>
        <div class="col-md-6">
            <label for="inputDescripcion" class="form-label">Descripción</label>
            <input type="text" class="form-control" id="inputDescripcion">
        </div>
        <div class="col-md-6">
            <label for="selectMarca" class="form-label">Marca</label>
            <select class="form-select" name="select" id="selectMarca">
                <option value="valor0" selected >Seleccione marca</option>
                <option value="value1">Marca 1</option>
                <option value="value2">Marca 2</option>
                <option value="value3">Marca 3</option>
            </select>
        </div>
        <div class="col-md-6">
            <label for="inputAnio" class="form-label">Año</label>
            <input type="number" class="form-control" id="inputAnio">
        </div>
        <div class="col-12 d-flex flex-row-reverse">
            <button type="submit" class="btn btn-primary mt-3">Guardar</button>
        </div>
    </form>

{% endblock %}