TallerChaPin/TallerChaPin/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from TallerChaPin.views import *
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('', home, name="home"),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('taller/', include('taller.urls')),
    path('ordenes/', include('ordenes.urls')),
    path('facturas/', include('facturas.urls')),
    path('reportes/', include ('reportes.urls')),
    path('taller/', template_taller, name='taller_home'),
    path('ordenes/', template_ordenes, name='ordenes_home'),
    path('facturas/', template_facturas, name='facturas_home'),
    path('listados/', template_listados, name='listados_home'),
    path('reportes/', template_reportes, name='reportes_home'),
    path('admin/', admin.site.urls),
    re_path(r'^docs/', include('docs.urls')),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
]

TallerChaPin/facturas/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    # ----------------Factura-------------------------
    path('facturas/crear/<int:pk>', crearFactura, name="crearFactura"),
    path('facturas/listar', FacturaListView.as_view(), name="listarFacturas"),
    path('facturas/detalle/<int:pk>',
         FacturaDetailView.as_view(), name="detallesFactura"),
    path('facturas/exportar',
         exportar_listado_facturas, name='exportarFacturas'),
    # ----------------Pago-------------------------
    path('pagos/crear/<int:pk>', PagoCreateView.as_view(), name="crearPago"),
    path('pagos/detalle/<int:pk>', PagoDetailView.as_view(), name="detallesPago"),
    # Solo se puede modificar el modo de pago...
    path('pagos/modificar/<int:pk>',
         PagoUpdateView.as_view(), name="modificarPago"),
    path('pagos/listar', PagoListView.as_view(), name="listarPagos"),
    path('pagos/eliminar/<int:pk>', PagoDeleteView.as_view(), name="eliminarPago"),
    path('pagos/exportar',
         exportar_listado_pagos, name='exportarPagos'),
    # ----------------PDF-------------------------
    path('factura/pdf/<int:pk>', imprimirFactura.as_view(),
         name='imprimirFactura'),
    path('pago/pdf/<int:pk>', imprimirPago.as_view(),
         name='imprimirPago'),

]

TallerChaPin/taller/urls.py
from django.urls import path
from .views import *


urlpatterns = [

     path('materiales/unidades_de_medida/<int:pk>', UnidadesDeMedida),
     path('cliente/vehiculos/<int:pk>', vehiculosDelCliente),
     # ----------------- MARCAS -----------------

     path('marcas/crear', MarcaCreateView.as_view(), name="crearMarca"),
     path('marcas/listar', MarcaListView.as_view(), name="listarMarcas"),
     path('marca/modificar/<int:pk>',
          MarcaUpdateView.as_view(), name="modificarMarca"),
     path('marca/eliminar/<int:pk>',
          MarcaDeleteView.as_view(), name="eliminarMarca"),
     path('marcas/exportar',
          exportar_listado_marcas, name='exportarMarcas'),
     # ----------------- TAREAS -----------------

     path('tarea/crear', TareaCreateView.as_view(), name="crearTarea"),
     path('tarea/modificar/<int:pk>',
          TareaUpdateView.as_view(), name="modificarTarea"),
     path('tarea/eliminar/<int:pk>',
          TareaDeleteView.as_view(), name="eliminarTarea"),
     path('tareas/listar', TareaListView.as_view(), name="listarTareas"),
     path('tareas/exportar',
          exportar_listado_tareas, name='exportarTareas'),

     # ----------------- TIPOS TAREA -----------------

     path('tipo-tarea/crear', TipoTareaCreateView.as_view(), name="crearTipoTarea"),
     path('tipo-tarea/modificar/<int:pk>',
          TipoTareaUpdateView.as_view(), name="modificarTipoTarea"),
     path('tipo-tarea/eliminar/<int:pk>',
          TipoTareaDeleteView.as_view(), name="eliminarTipoTarea"),
     path('tipo-tarea/listar', TipoTareaListView.as_view(), name="listarTipoTarea"),
     path('tipo-tarea/exportar',
          exportar_listado_tipotareas, name='exportarTipoTareas'),
     # ----------------- REPUESTOS -----------------

     path('repuesto/crear', RepuestoCreateView.as_view(), name="crearRepuesto"),
     path('repuestos/listar', RepuestoListView.as_view(), name="listarRepuestos"),
     path('repuesto/modificar/<int:pk>',
          RepuestoUpdateView.as_view(), name="modificarRepuesto"),
     path('repuesto/eliminar/<int:pk>',
          RepuestoDeleteView.as_view(), name="eliminarRepuesto"),
     path('repuestos/exportar',
          exportar_listado_repuestos, name='exportarRepuestos'),
     # ----------------- MODELO -----------------

     path('modelo/crear', ModeloCreateView.as_view(), name="crearModelo"),
     path('modelos/listar', ModeloListView.as_view(), name="listarModelos"),
     path('modelo/modificar/<int:pk>',
          ModeloUpdateView.as_view(), name="modificarModelo"),
     path('modelo/eliminar/<int:pk>',
          ModeloDeleteView.as_view(), name="eliminarModelo"),
     path('modelos/exportar',
          exportar_listado_modelos, name='exportarModelos'),
     # ----------------- MATERIALES -----------------

     path('materiales/listar', MaterialListView.as_view(), name="listarMateriales"),
     path('materiales/crear', MaterialCreateView.as_view(), name="crearMaterial"),
     path('materiales/eliminar/<int:pk>',
          MaterialDeleteView.as_view(), name="eliminarMaterial"),
     path('materiales/modificar/<int:pk>',
          MaterialUpdateView.as_view(), name="modificarMaterial"),
     path('materiales/modificarCantidad',
          MaterialCantidad, name="modificarCantidad"),
     path('materiales/exportar',
          exportar_listado_materiales, name='exportarMateriales'),
     # ----------------- TIPOS MATERIALES -----------------

     path('tipos-materiales/crear', 
          TipoMaterialCreateView.as_view(), name="crearTipoMaterial"),
     path('tipos-materiales/listar', 
          TipoMaterialListView.as_view(), name="listarTipoMateriales"),
     path('tipos-materiales/modificar/<int:pk>',
          TipoMaterialUpdateView .as_view(), name="modificarTipoMaterial"),
     path('tipos-materiales/eliminar/<int:pk>',
          TipoMaterialDeleteView.as_view(), name="eliminarTipoMaterial"),
     path('tipo-materiales/exportar',
          exportar_listado_tipomateriales, name='exportarTipoMateriales'),
     # ----------------- CLIENTES -----------------

     path('clientes/listar', 
          ClienteListView.as_view(), name='listarClientes'),
     path('clientes/crear', 
          ClienteCreateView.as_view(), name='crearCliente'),
     path('clientes/modificar/<int:pk>',
          ClienteUpdateView .as_view(), name="modificarCliente"),
     path('clientes/eliminar/<int:pk>',
          ClienteDeleteView.as_view(), name="eliminarCliente"),
     path('clientes/exportar',
          exportar_listado_clientes, name='exportarClientes'),
     # ----------------- VEHÍCULOS -----------------

     path('vehiculos/listar', 
          VehiculoListView.as_view(), name="listarVehiculos"),
     path('vehiculos/crear', 
          VehiculoCreateView.as_view(), name="crearVehiculo"),
     path('vehiculos/modificar/<int:pk>',
          VehiculoUpdateView.as_view(), name="modificarVehiculo"),
     path('vehiculos/eliminar/<int:pk>',
          VehiculoDeleteView.as_view(), name="eliminarVehiculo"),
     path('vehiculos/exportar',
          exportar_listado_vehiculos, name='exportarVehiculos'),
     # ----------------- EMPLEADOS -----------------

     # path('empleado/registro_usuario/<int:pk>',
     #      RegistrarUsuarioCreateView.as_view(), name="registroEmpleado"),
     path('empleado/imprimir_pdf/<int:pk>',
          imprimirUsuarioEmpleado.as_view(), name="usuarioPDF"),
     path('empleado/registrar',
          EmpleadoCreateView.as_view(), name="crearEmpleado"),
     path('empleado/modificar/<int:pk>',
          EmpleadoUpdateView.as_view(), name="modificarEmpleado"),
     path('empleado/eliminar/<int:pk>',
          EmpleadoDeleteView.as_view(), name="eliminarEmpleado"),
     path('empleados/listar', 
          EmpleadoListView.as_view(), name="listarEmpleados"),
     path('empleados/exportar',
          exportar_listado_empleados, name='exportarEmpleados'),
     path('empleado/asociar_tarea/<int:pk>',
          asociar_tarea_empleado, name='asociarTarea'),
]

TallerChaPin/facturas/models.py
from django.forms import ValidationError
from django.utils.timezone import now
from django.db import models
from ordenes.models import OrdenDeTrabajo


# Aqui definimos los modelos:

#-------------------------- FACTURA -------------------------------#

class Factura(models.Model):
    CREADA = 0
    ACTIVA = 1
    CANCELADA = 2
    PAGADA = 3
    VENCIDA = 4
    ESTADO_CHOICES = [
        (CREADA, 'Creada'),
        (ACTIVA, 'Activa'),
        (CANCELADA, 'Cancelada'),
        (PAGADA, 'Pagada'),
        (VENCIDA, 'Vencida'),        
    ]

    orden = models.ForeignKey(OrdenDeTrabajo, related_name='factura', on_delete=models.CASCADE)
    fecha = models.DateField()
    estado =  models.PositiveBigIntegerField(
        choices=ESTADO_CHOICES, default=CREADA)
    cuotas = models.PositiveSmallIntegerField(default=1, blank=False, null=False)

    # @property
    # def vehiculo(self):
    #     return self.orden.vehiculo

    # @property
    # def cliente(self):
    #     return self.orden.cliente

    @staticmethod
    def facturar_orden(orden):
        factura = Factura.objects.create(orden=orden, fecha=now())
        for des, precio in [(f"{m}", m.precio()) for m in orden.orden_materiales.all()]:
            factura.agregar_detalle(des, precio)
        for desc, precio in [(f"{r}", r.precio()) for r in orden.orden_repuestos.all()]:
            factura.agregar_detalle(desc, precio)
        for desc, precio in [(f"{t}", t.precio()) for t in orden.detalles.all()]:
            factura.agregar_detalle(desc, precio)

        #Decrementar materiales utilizados
        for m in [m for m in orden.orden_materiales.all()]:
            m.decrementar_materiales(m)

        #Decrementar repuestos utilizados
        for r in [r for r in orden.orden_repuestos.all()]:
            r.decrementar_repuesto(r)

        #Actualizar estado de la orden        
        orden.actualizar_estado(OrdenDeTrabajo.FACTURAR_ORDEN)
        orden.save()
       
        return factura

    def total(self):
        return self.detalles.aggregate(total=models.Sum('precio'))['total']

    def pagado(self):
        return self.estado == Factura.PAGADA

    def puede_pagar(self):
        return self.adeuda()

    def get_cliente_orden(self):
        return self.orden.cliente

    def get_vehiculo_orden(self):
        return self.orden.vehiculo

    def get_cuotas(self):
        return self.cuotas

    def get_estado(self):
        return self.get_estado_display()

    def no_pagada(self):
        return self.orden.estado !=  OrdenDeTrabajo.FINALIZADA
    
    def adeuda(self):
        return self.saldo() > 0

    def agregar_detalle(self, descripcion, precio):
        return DetalleFactura.objects.create(factura=self, descripcion=descripcion, precio=precio)

    def pagar(self, monto, tipo, num_cuotas):

        if monto <= 0:
            raise ValidationError('El monto a pagar debe ser mayor.')

        if monto > self.saldo():
            raise ValidationError('El pago ingresado es mayor al saldo restante.')

        if tipo == Pago.TARJETA_CREDITO and monto != self.saldo():
            raise ValidationError('El pago con tarjeta de crédito solo está disponible para pagos totales.')

        pago = Pago.objects.create(factura=self, monto=monto, tipo=tipo)
        self.estado = Factura.ACTIVA

        if tipo == Pago.TARJETA_CREDITO:
            self.cuotas = num_cuotas
        else:
            self.cuotas = 1

        if self.saldo() <= 0:
            self.estado = Factura.PAGADA
            self.orden.pagar_orden()

        self.save()
        
        return pago

    def saldo(self):
        saldo = self.total() - (self.pagos.aggregate(total=models.Sum('monto'))['total'] or 0) 
        return round(saldo, 2 )
 

#-------------------------- DETALLE FACTURA -------------------------------#

class DetalleFactura(models.Model):
    factura = models.ForeignKey(
        Factura, related_name="detalles", on_delete=models.CASCADE)
    descripcion = models.CharField(max_length=100)
    precio = models.DecimalField(max_digits=10, decimal_places=2)

#-------------------------------- PAGO -----------------------------------#

class Pago(models.Model):
    
    CONTADO = 0
    TARJETA_DEBITO = 1
    TARJETA_CREDITO = 2
    TIPO_PAGO = [
        (CONTADO, 'Contado'),
        (TARJETA_DEBITO, 'Tarjeta Debito'),
        (TARJETA_CREDITO, 'Tarjeta Credito'),
    ]
    factura = models.ForeignKey(
        Factura, on_delete=models.CASCADE, related_name="pagos")
    fecha = models.DateField(auto_now=True)
    monto = models.DecimalField(max_digits=10, decimal_places=2)
    tipo = models.PositiveSmallIntegerField(
        choices=TIPO_PAGO, default=CONTADO)

    def __str__(self):
        return f'Nro. de Factura: ({self.factura.pk})'

    def puede_eliminarse(self):
        return self.factura.estado == Factura.ACTIVA or self.factura.estado == Factura.CREADA

    @property
    def cliente(self):
        return self.factura.orden.cliente

    def get_cuotas(self):
        return self.factura.get_cuotas()

    def get_nombre_factura(self):
        return f'Nro. de Factura: ({self.factura.pk})'
    
    def get_tipo(self):
        return self.get_tipo_display()
        
    def puede_pagar(self):
        return self.factura.puede_pagar()

TallerChaPin/facturas/templates/facturas/factura_confirm_delete.html
{% extends 'modal_confirm.html' %}

{% load static %}

{% block modal_title %} Eliminar factura {% endblock %}

{% block modal_body %}
    <p id="modal-msj"></p>
{% endblock %}

{% block extrajs %} {% endblock %}

TallerChaPin/facturas/templates/facturas/factura_form.html
{% extends 'template_facturas.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block main %}
<div class="col-8">
    <h3>{{ titulo }}</h3>
    {% crispy form form.helper %}
</div>
{% endblock %}

TallerChaPin/facturas/templates/facturas/factura_list.html
{% extends 'template_facturas.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
{{titulo}}
{% endblock %}
{% block main %}
<h1>{{titulo}}</h1>

<div class="table-responsive">
  <table class="table table-hover {% if filtros %} sortable{% endif %}">
    <thead>
      <tr>
        {% for sortable in filtros.sortables %}
        <th class="sortable" scope="col" data-s-field={{sortable.0}}>{{sortable.1}}</th>
        {% endfor %}
        <th scope="col">Opciones</th>
      </tr>
    </thead>
    <tbody>
      {% for factura in object_list %}
      <tr>
        <td>{{ factura.orden.pk }}</td>
        <td>{{ factura.fecha }}</td>
        <td>{{ factura.orden.cliente }}</td>
        <td>{{ factura.orden.vehiculo }}</td>
        <td>{{ factura.get_estado_display}}</td>

        <td>
          {% if perms.facturas.view_factura %}
          <a href="{% url 'detallesFactura' factura.pk %}" class="btn-listado btn-ver">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye"
              viewBox="0 0 16 16">
              <path
                d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z" />
              <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z" />
            </svg>
            {% endif %}
        </td>
      </tr>
      {% empty %}
      <tr>
        <td>No hay facturas</td>
        <td>n/a</td>
        <td>n/a</td>
        <td>n/a</td>
        <td>n/a</td>
        <td>n/a</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<div class="col-12 d-flex flex-row-reverse mb-4">
  <a href="{% url 'exportarFacturas'  %}?{{ request.GET.urlencode }}
    "type="submit" class="btn btn-primary mt-3" data-toggle="tooltip" data-placement="top" title="Exporta el listado a CSV">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download"
      viewBox="0 0 16 16">
      <path
        d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z" />
      <path
        d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z" />
    </svg>
    Descargar listado</a>
</div>


{% endblock %}

{% block filtros%}
<div>
  {% crispy filtros filtros.helper %}
</div>
{% endblock %}

{% block modals %}
{% endblock %}

{% block extrajs %}
<script>
  conectarBotonesAModal('.btn-eliminar', 'modalEliminarPago');
</script>
{% endblock %}

TallerChaPin/facturas/templates/facturas/pago_confirm_delete.html
{% extends 'modal_confirm.html' %}

{% load static %}

{% block modal_title %} Eliminar pago {% endblock %}

{% block modal_body %}
    <p id="modal-msj"></p>
{% endblock %}

{% block extrajs %} {% endblock %}

TallerChaPin/facturas/templates/facturas/pago_detail.html
{% extends 'template_facturas.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block main %}

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container">

    <div class="wrapper wrapper-content animated fadeInRight">

        <div class="ibox-title">
            <h1 class="mb-4 ">Pago: #{{ object.pk }}</h1>
        </div>

        <div class="row">

            <div class="col">
                <div class="ibox border border-primary rounded p-3 h-100 p-4">
                    <h3>
                        {{ object.factura.orden.cliente.nombre }}, {{ object.factura.orden.cliente.apellido }}
                    </h3>
                    <span>
                        <i class="fas fa-car-side"></i> {{ object.factura.orden.vehiculo.patente }}
                        ({{object.factura.orden.vehiculo.modelo}}) <br>
                    </span>
                </div>
            </div>
        </div>

        <div class="row mt-4">
            <div class="col-md-4">
                <div
                    class="ibox border border-primary rounded p-3 h-100 d-flex justify-content-center flex-column align-items-center">
                    <div class="ibox-title">
                        <h5> Total pagado </h5>
                    </div>
                    <div class="ibox-content">
                        <h2 class="font-bold text-primary">
                            <i class="fas fa-dollar-sign"></i>
                            {{ object.monto }}
                        </h2>
                    </div>
                    <div class="ibox-title">
                        <h5> Saldo restante </h5>
                    </div>
                    <div class="ibox-content">
                        <h2 class="font-bold text-primary">
                            <i class="fas fa-dollar-sign"></i> {{pago.factura.saldo}}
                        </h2>
                    </div>
                </div>
            </div>
        
            <div class="col-md-4">
                <div
                    class="ibox border border-primary rounded p-3 h-100 d-flex justify-content-center flex-column align-items-center">
                    <div class="ibox-title">
                        <h5> Total a pagar</h5>
                    </div>
                    <div class="ibox-content">
                        <h2 class="font-bold text-primary">
                            <i class="fas fa-dollar-sign"></i>
                            {{object.factura.orden.precio_orden}}
                        </h2>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="border border-primary rounded p-3">
                    <h5>Acciones</h5>
                    {% if perms.facturas.delete_pago %}
                    <a href="" data-bs-toggle="modal" data-bs-target="#modalEliminarPago"
                        data-bs-nombre="{{ pago.factura.orden.cliente.nombre  }}" data-bs-url="{% url 'eliminarPago' object.pk %}"
                        class="btn-eliminar btn btn-danger m-1 w-100"><i class="fas fa-trash-alt"></i>
                        Eliminar Pago</a>
                    {% endif %}
                    {% if perms.facturas.view_factura %}
                    <a href="{% url 'detallesFactura' object.factura.pk %}" class="btn btn-primary m-1 w-100"><i class="fas fa-eye"></i> Ver Factura </a>
                    {% endif %}
                </div>

            </div>
        </div>

    </div>
    <div class="row mt-4">
        <div class="col-md-12 mt-2">
            <div class="ibox-content">
                <div class="ibox-content mb-4">
                    <a href="{% url 'imprimirPago' object.pk %}" class="btn btn-primary pull-right"><i
                            class="fa fa-print" aria-hidden="true"></i>
                        Imprimir</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block modals %}
{% include './pago_confirm_delete.html' with idModal='modalEliminarPago' %}
{% endblock %}

{% block extrajs %}
<script>
  conectarBotonesAModal('.btn-eliminar', 'modalEliminarPago');
</script>
{% endblock %}

TallerChaPin/facturas/templates/facturas/pago_form.html
{% extends 'template_facturas.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block main %}
<div class="col-8">
    <h3>
        {{ titulo }}
    </h3>
        <div class="col-12">
                {% comment %} <a href="{% url 'pagoDebito' object.pk %}" class="btn btn-success m-1 w-100" id="liveAlertBtn">
                    <i class="fas fa-check-circle"></i> Pagar con debito</a>
                <a href="{% url 'pagoCredito' object.pk %}" class="btn btn-success m-1 w-100" id="liveAlertBtn">
                    <i class="fas fa-check-circle"></i> Pagar con credito</a>
                <a href="{% url 'pagoContado' object.pk %}" class="btn btn-success m-1 w-100" id="liveAlertBtn">
                    <i class="fas fa-check-circle"></i> Pagar al contado</a> {% endcomment %}
        </div>
</div>
{% endblock %}

TallerChaPin/facturas/templates/facturas/pago_list.html
{% extends 'template_facturas.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
{{titulo}}
{% endblock %}
{% block main %}
<h1>{{titulo}}</h1>

<div class="table-responsive">
  <table class="table table-hover {% if filtros %} sortable{% endif %}">
    <thead>
      <tr>
        {% for sortable in filtros.sortables %}
        <th class="sortable bg-transition pointer" scope="col" data-s-field={{sortable.0}}>{{sortable.1}}</th>
        {% endfor %}
        <th scope="col">Opciones</th>
      </tr>
    </thead>
    <tbody>
      {% for pago in object_list %}
      <tr>
        <td>{{ pago.pk }}</td>
        <td>{{ pago.factura.orden.cliente }}</td>
        <td>{{ pago }}</td>
        <td>{{ pago.fecha }}</td>
        <td>{{ pago.monto }}</td>
        <td>{{ pago.get_tipo_display }}</td>
        <td>{{ pago.factura.cuotas }}</td>


        <td>
          {% if perms.facturas.view_pago %}
          <a href="{% url 'detallesPago' pago.pk %}" class="btn-listado btn-ver">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye"
              viewBox="0 0 16 16">
              <path
                d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z" />
              <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z" />
            </svg>
            </svg></a>
          {% endif %}
          {% if perms.facturas.delete_pago %}
          <a href="" data-bs-toggle="modal" data-bs-target="#modalEliminarPago"
            data-bs-nombre="{{ pago.factura.orden.cliente.nombre }}" data-bs-url="{% url 'eliminarPago' pago.pk %}"
            class="btn-eliminar btn-listado"><i class="fas fa-trash-alt"></i>
          </a>
          {% endif %}

        </td>

      </tr>
      {% empty %}
      <tr>
        <td>No hay pagos</td>
        <td>n/a</td>
        <td>n/a</td>
        <td>n/a</td>
        <td>n/a</td>
        <td>n/a</td>
        <td>n/a</td>
        <td>n/a</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<div class="col-12 d-flex flex-row-reverse mb-4">
  <a href="{% url 'exportarPagos'  %}?{{ request.GET.urlencode }}
    "type="submit" class="btn btn-primary mt-3" data-toggle="tooltip" data-placement="top" title="Exporta el listado a CSV">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download"
      viewBox="0 0 16 16">
      <path
        d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z" />
      <path
        d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z" />
    </svg>
    Descargar listado</a>
</div>


{% endblock %}

{% block filtros%}
<div>
  {% crispy filtros filtros.helper %}
</div>
{% endblock %}

{% block modals %}
{% include './factura_confirm_delete.html' with idModal='modalEliminarPago' %}
{% endblock %}

{% block extrajs %}
<script>
  conectarBotonesAModal('.btn-eliminar', 'modalEliminarPago');
</script>
{% endblock %}