TallerChaPin/TallerChaPin/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from TallerChaPin.views import *
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('', home, name="home"),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('taller/', include('taller.urls')),
    path('ordenes/', include('ordenes.urls')),
    path('facturas/', include('facturas.urls')),
    path('reportes/', include ('reportes.urls')),
    path('taller/', template_taller, name='taller_home'),
    path('ordenes/', template_ordenes, name='ordenes_home'),
    path('facturas/', template_facturas, name='facturas_home'),
    path('listados/', template_listados, name='listados_home'),
    path('reportes/', template_reportes, name='reportes_home'),
    path('admin/', admin.site.urls),
    re_path(r'^docs/', include('docs.urls')),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
]

TallerChaPin/taller/urls.py
from django.urls import path
from .views import *


urlpatterns = [

     path('materiales/unidades_de_medida/<int:pk>', UnidadesDeMedida),
     path('cliente/vehiculos/<int:pk>', vehiculosDelCliente),
     # ----------------- MARCAS -----------------

     path('marcas/crear', MarcaCreateView.as_view(), name="crearMarca"),
     path('marcas/listar', MarcaListView.as_view(), name="listarMarcas"),
     path('marca/modificar/<int:pk>',
          MarcaUpdateView.as_view(), name="modificarMarca"),
     path('marca/eliminar/<int:pk>',
          MarcaDeleteView.as_view(), name="eliminarMarca"),
     path('marcas/exportar',
          exportar_listado_marcas, name='exportarMarcas'),
     # ----------------- TAREAS -----------------

     path('tarea/crear', TareaCreateView.as_view(), name="crearTarea"),
     path('tarea/modificar/<int:pk>',
          TareaUpdateView.as_view(), name="modificarTarea"),
     path('tarea/eliminar/<int:pk>',
          TareaDeleteView.as_view(), name="eliminarTarea"),
     path('tareas/listar', TareaListView.as_view(), name="listarTareas"),
     path('tareas/exportar',
          exportar_listado_tareas, name='exportarTareas'),

     # ----------------- TIPOS TAREA -----------------

     path('tipo-tarea/crear', TipoTareaCreateView.as_view(), name="crearTipoTarea"),
     path('tipo-tarea/modificar/<int:pk>',
          TipoTareaUpdateView.as_view(), name="modificarTipoTarea"),
     path('tipo-tarea/eliminar/<int:pk>',
          TipoTareaDeleteView.as_view(), name="eliminarTipoTarea"),
     path('tipo-tarea/listar', TipoTareaListView.as_view(), name="listarTipoTarea"),
     path('tipo-tarea/exportar',
          exportar_listado_tipotareas, name='exportarTipoTareas'),
     # ----------------- REPUESTOS -----------------

     path('repuesto/crear', RepuestoCreateView.as_view(), name="crearRepuesto"),
     path('repuestos/listar', RepuestoListView.as_view(), name="listarRepuestos"),
     path('repuesto/modificar/<int:pk>',
          RepuestoUpdateView.as_view(), name="modificarRepuesto"),
     path('repuesto/eliminar/<int:pk>',
          RepuestoDeleteView.as_view(), name="eliminarRepuesto"),
     path('repuestos/exportar',
          exportar_listado_repuestos, name='exportarRepuestos'),
     # ----------------- MODELO -----------------

     path('modelo/crear', ModeloCreateView.as_view(), name="crearModelo"),
     path('modelos/listar', ModeloListView.as_view(), name="listarModelos"),
     path('modelo/modificar/<int:pk>',
          ModeloUpdateView.as_view(), name="modificarModelo"),
     path('modelo/eliminar/<int:pk>',
          ModeloDeleteView.as_view(), name="eliminarModelo"),
     path('modelos/exportar',
          exportar_listado_modelos, name='exportarModelos'),
     # ----------------- MATERIALES -----------------

     path('materiales/listar', MaterialListView.as_view(), name="listarMateriales"),
     path('materiales/crear', MaterialCreateView.as_view(), name="crearMaterial"),
     path('materiales/eliminar/<int:pk>',
          MaterialDeleteView.as_view(), name="eliminarMaterial"),
     path('materiales/modificar/<int:pk>',
          MaterialUpdateView.as_view(), name="modificarMaterial"),
     path('materiales/modificarCantidad',
          MaterialCantidad, name="modificarCantidad"),
     path('materiales/exportar',
          exportar_listado_materiales, name='exportarMateriales'),
     # ----------------- TIPOS MATERIALES -----------------

     path('tipos-materiales/crear', 
          TipoMaterialCreateView.as_view(), name="crearTipoMaterial"),
     path('tipos-materiales/listar', 
          TipoMaterialListView.as_view(), name="listarTipoMateriales"),
     path('tipos-materiales/modificar/<int:pk>',
          TipoMaterialUpdateView .as_view(), name="modificarTipoMaterial"),
     path('tipos-materiales/eliminar/<int:pk>',
          TipoMaterialDeleteView.as_view(), name="eliminarTipoMaterial"),
     path('tipo-materiales/exportar',
          exportar_listado_tipomateriales, name='exportarTipoMateriales'),
     # ----------------- CLIENTES -----------------

     path('clientes/listar', 
          ClienteListView.as_view(), name='listarClientes'),
     path('clientes/crear', 
          ClienteCreateView.as_view(), name='crearCliente'),
     path('clientes/modificar/<int:pk>',
          ClienteUpdateView .as_view(), name="modificarCliente"),
     path('clientes/eliminar/<int:pk>',
          ClienteDeleteView.as_view(), name="eliminarCliente"),
     path('clientes/exportar',
          exportar_listado_clientes, name='exportarClientes'),
     # ----------------- VEHÍCULOS -----------------

     path('vehiculos/listar', 
          VehiculoListView.as_view(), name="listarVehiculos"),
     path('vehiculos/crear', 
          VehiculoCreateView.as_view(), name="crearVehiculo"),
     path('vehiculos/modificar/<int:pk>',
          VehiculoUpdateView.as_view(), name="modificarVehiculo"),
     path('vehiculos/eliminar/<int:pk>',
          VehiculoDeleteView.as_view(), name="eliminarVehiculo"),
     path('vehiculos/exportar',
          exportar_listado_vehiculos, name='exportarVehiculos'),
     # ----------------- EMPLEADOS -----------------

     # path('empleado/registro_usuario/<int:pk>',
     #      RegistrarUsuarioCreateView.as_view(), name="registroEmpleado"),
     path('empleado/imprimir_pdf/<int:pk>',
          imprimirUsuarioEmpleado.as_view(), name="usuarioPDF"),
     path('empleado/registrar',
          EmpleadoCreateView.as_view(), name="crearEmpleado"),
     path('empleado/modificar/<int:pk>',
          EmpleadoUpdateView.as_view(), name="modificarEmpleado"),
     path('empleado/eliminar/<int:pk>',
          EmpleadoDeleteView.as_view(), name="eliminarEmpleado"),
     path('empleados/listar', 
          EmpleadoListView.as_view(), name="listarEmpleados"),
     path('empleados/exportar',
          exportar_listado_empleados, name='exportarEmpleados'),
     path('empleado/asociar_tarea/<int:pk>',
          asociar_tarea_empleado, name='asociarTarea'),
]

TallerChaPin/taller/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.core.exceptions import ValidationError
from datetime import date
from django.core.validators import MinValueValidator

# Create your models here.
# http://....../?atributo__contains=valor
# FILTRO = {'atributo__contains': valor}
# ...?nombre__icontains=a&marca__exact=1


def validacion_nombre_unico(modelo, campo, value):
    aux = dict([(f"{campo}__iregex", f'^{value}$')])
    if modelo.objects.filter(**aux).exists():
        raise ValidationError({"nombre": "nombre ya existe"}) #TODO: se muestran con un formato malo
    # return validateeven


def texto_to_query(texto):
    filtros = dict([chunk.split("=") for chunk in texto.split("&")])
    filtro = models.Q()
    for attr, value in filtros.items():
        if value.isdigit():
            value = int(value)
        filtro &= models.Q(**{attr: value})
    return filtro


class MarcaQuerySet(models.QuerySet):
    def filtrar(self, texto):
        return self.filter(texto_to_query(texto))


class Marca(models.Model):
    nombre = models.CharField(max_length=50, unique=True)
    descripcion = models.CharField(max_length=200, blank=True)
    objects = MarcaQuerySet.as_manager()

    def __str__(self):
        return self.nombre

    def clean(self) -> None:
        validacion_nombre_unico(Marca, "nombre", self.nombre)
        return super().clean()


class ModeloQuerySet(models.QuerySet):
    def filtrar(self, texto):
        return self.filter(texto_to_query(texto))

def anio_valido(anio):
    if anio > date.today().year:
        raise ValidationError('El año del modelo no puede ser mayor al año actual')
class Modelo(models.Model):
    nombre = models.CharField(max_length=50, unique=True)
    descripcion = models.CharField(max_length=200, blank=True)
    marca = models.ForeignKey(
        Marca, related_name="modelos", on_delete=models.RESTRICT)
    anio = models.PositiveSmallIntegerField(validators=[anio_valido])

    # Manager de la clase Modelo
    objects = ModeloQuerySet.as_manager()

    def __str__(self):
        return f"{self.nombre}, {self.marca}"

    def clean(self) -> None:
        validacion_nombre_unico(Modelo, "nombre", self.nombre)
        return super().clean()


class TipoTarea(models.Model):
    nombre = models.CharField(max_length=50, unique=True)
    descripcion = models.CharField(max_length=200, blank=True)
    # Requiere Material[si/no]
    materiales = models.BooleanField(default=False)
    # Requiere Repuesto[si/no]
    repuestos = models.BooleanField(default=False)
    # Requiere Planilla[si/no]
    planilla = models.BooleanField(default=False)

    def __str__(self):
        return self.nombre

    def clean(self) -> None:
        validacion_nombre_unico(TipoTarea, "nombre", self.nombre)
        return super().clean()

    def get_req_materiales(self):
        return self.materiales
    
    def get_req_repuestos(self):
        return self.repuestos
    
    def get_req_planilla(self):
        return self.planilla

class Tarea(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=200, blank=True)
    tipo = models.ForeignKey(TipoTarea, on_delete=models.RESTRICT)
    precio = models.DecimalField(max_digits=10, decimal_places=2, validators = [MinValueValidator(0)])

    def __str__(self):
        return self.nombre

    def eliminable(self, presupuesto_id):
        presupuestos = self.presupuestos.filter(pk=presupuesto_id)
        if presupuestos.exists():
            presupuesto = presupuestos.first()
            if presupuesto.orden:
                detalles = presupuesto.orden.detalles.filter(tarea=self)
                return not (detalles.exists() and detalles.first().exitosa)
        return True

class Repuesto(models.Model):
    TIPOS = (
        (1, 'Puerta'),
        (2, 'Guardabarros'),
        (3, 'Parabrisa'),
        (4, 'Cristal'),
        (5, 'Bateria'),
        (6, 'Rueda'),
        (7, 'Mecanico'),
        (8, 'Llanta'),
        (9, 'Suspension'),
        (10, 'Aire Acondicionado'),
        (99, 'Otro'),
    )
    nombre = models.CharField(max_length=50)
    modelo = models.ForeignKey(Modelo, on_delete=models.RESTRICT)
    tipo = models.PositiveSmallIntegerField(choices=TIPOS)
    cantidad = models.IntegerField(blank=True, null=True, default=0, validators = [MinValueValidator(0)])
    precio = models.DecimalField(max_digits=10, decimal_places=2, blank=True, validators = [MinValueValidator(0)])

    def __str__(self):
        return f"{self.nombre}, {self.modelo}"

    def get_tipo(self):
        return self.get_tipo_display()
    
    def decrementar_stock(self,cantidad):
        self.cantidad -= cantidad
        self.save()

class TipoMaterial(models.Model):
    GRAMO = 1
    CM3 = 2
    LITRO = 3
    UNIDAD = 4
    KG = 5
    METRO = 6
    METRO2 = 7
    UNIDADES_BASICAS = (
        (GRAMO, "g"),
        (CM3, "CM3"),
        (UNIDAD, "Unidad/es"),  # Por unidad
        (METRO, "Metro/s"),
        (METRO2, "Metro2")
    )
    # Ejemplos: Remaches, Lijas, Fibra, Resina, Pintura, Masilla, Cinta
    nombre = models.CharField(max_length=50, unique=True)
    unidad_medida = models.PositiveSmallIntegerField(choices=UNIDADES_BASICAS)

    def __str__(self):
        return self.nombre

    # def clean(self) -> None:
    #     validacion_nombre_unico(TipoMaterial, "nombre", self.nombre)
    #     return super().clean()
    def get_unidad_medida(self):
        return self.get_unidad_medida_display()


class Material(models.Model):
    nombre = models.CharField(max_length=50)
    tipo = models.ForeignKey(TipoMaterial, on_delete=models.RESTRICT)
    cantidad = models.IntegerField(blank=True, null=True, default=0)
    precio = models.DecimalField(max_digits=10, decimal_places=2, blank=True, validators = [MinValueValidator(0)])

    def __str__(self):
        return f"{self.nombre} ({self.tipo}) {self.tipo.get_unidad_medida_display()}"

    def decrementar_stock(self, cantidad):
        self.cantidad -= cantidad
        self.save()

    def stock(self):
        return self.cantidad

    def calcular_precio(self, cantidad):
        return self.precio * cantidad


class Cliente(models.Model):
    dni = models.CharField(max_length=8, unique=True)
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    direccion = models.CharField(max_length=100)
    telefono = models.CharField(max_length=50)
    
    def __str__(self):
        return f'{self.nombre} {self.apellido} ({self.dni})'
        
    def get_nombre_abreviado(self):
        return f'{self.nombre[0]}. {self.apellido}'

    def vip(self):
        # Obtener ultimas tres facturas pagas del cliente
        # Ir a los presupuestos
        # Tomar un presupuesto
        # si ese presupuesto tiene una orden, esta confirmado
        # Si la orden tiene una factura, esta facturada
        # ver si las ultimas 3 facturas
        # si hay 3 facturas pagadas es vip, caso contrario no es vip 
        facturas = []
        for presupuesto in self.presupuestos.all():   
            if (presupuesto.orden) != None and (presupuesto.orden.factura) != None:              
                    facturas.extend(presupuesto.orden.factura.all())
            else:
                return False  
        # Veo las ultimas 4, puede adeudar al menos una al ser VIP
        facturas = sorted(facturas, key=lambda f: f.fecha , reverse=True)[:4]
        if len(facturas) >= 4 and not facturas[0].pagado():
            facturas.pop(0) #De estar la mas reciente impaga la quita del listado. VER ESTO 
        return len(facturas) >= 3 and all(f.pagado() for f in facturas) 

def validar_anio(anio):
    if anio < date.today().year - 12:
        raise ValidationError('El vehículo tiene más de 12 años de antigüedad')
    if anio > date.today().year:
        raise ValidationError('El año del vehículo no puede ser mayor al año actual')

class Vehiculo(models.Model):
    cliente = models.ForeignKey(
        Cliente, related_name="vehiculos", on_delete=models.RESTRICT)
    patente = models.CharField(max_length=7, unique=True)
    modelo = models.ForeignKey(Modelo, on_delete=models.RESTRICT)
    anio = models.IntegerField(validators=[validar_anio])
    chasis = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.modelo} - {self.patente}"


class Empleado(models.Model):
    cuil = models.CharField(max_length=13, unique=True)
    legajo = models.IntegerField(null=False)
    nombre = models.CharField(max_length=100, null=False, blank=False)
    apellido = models.CharField(max_length=100, null=False, blank=False)
    tareas = models.ManyToManyField(TipoTarea, related_name="empleados")
    usuario = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)

    def crear_usuario(self):
        base_username = (self.nombre[0] + self.apellido).lower()
        cantidad = User.objects.filter(username__startswith=base_username).count()
        if cantidad == 0:
            username = f"{base_username}"
        else:
            username = f"{base_username}{cantidad}"

        user = User.objects.create_user(
            username=username, password=self.cuil, first_name=self.nombre, last_name=self.apellido)
 
        self.usuario = user
        self.save()
        return user

     
    def añadir_grupos(self, grupos):
        if grupos:
            grupos_obj = [Group.objects.get(name=g) for g in grupos]
            self.usuario.groups.add(*grupos_obj)
            self.usuario.save()
            

    def get_tareas(self):
        tareas = self.tareas.all()
        return ' | '.join([t.nombre for t in tareas]) if tareas is not None else None
    
    def get_grupos(self):
        grupos = Group.objects.filter(user = self.usuario)
        return ', '.join([g.name for g in grupos]) if grupos is not None else None

    def es_admin(self):
        return self.usuario.groups.filter(name='Administrativo').exists()
    

TallerChaPin/templates/sidebar_facturas.html
<div class="flex-shrink-0 p-3 bg-white" style="width: 280px">
  <a
    href="/"
    class="
      d-flex
      align-items-center
      pb-3
      mb-3
      link-dark
      text-decoration-none
      border-bottom
    "
  >
    <svg class="bi me-2" width="30" height="24">
      <use xlink:href="#bootstrap"></use>
    </svg>
    <span class="fs-5 fw-semibold">Gestion de facturas</span>
  </a>
  <ul class="list-unstyled ps-0">
    <!-- Pagos -->
    <li class="mb-1">
      {% if perms.facturas.view_pago %}
      <button
        class="btn btn-toggle align-items-center rounded collapsed"
        data-bs-toggle="collapse"
        data-bs-target="#pagos-collapse"
        aria-expanded="false"
      >
        Pagos
      </button>

      <!-- Desplegable de pagos -->
      
      <div class="collapse" id="pagos-collapse">
        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
          {% if perms.ordenes.view_ordendetrabajo %}
          <li>
            <a href="{% url 'listarOrdenes' %}" class="link-dark rounded"
              >Facturar Órdenes
            </a>
          </li>
          {% endif %}
          {% if perms.facturas.view_factura %}
          <li>
            <a href="{% url 'listarFacturas' %}" class="link-dark rounded"
              >Listado de facturas</a
            >
          </li>
          {% endif %}
          {% if perms.facturas.view_pago %}
          <li>
            <a href="{% url 'listarPagos' %}" class="link-dark rounded"
              >Listado de pagos</a
            >
          </li>
          {% endif %}
        </ul>
      </div>
      {% endif %}
    </li>

    <!-- Clientes -->
    
    <li class="mb-1">
      {% if perms.taller.view_cliente %}
      <button
        class="btn btn-toggle align-items-center rounded collapsed"
        data-bs-toggle="collapse"
        data-bs-target="#clientes-collapse"
        aria-expanded="false"
      >
        Clientes
      </button>
      
      <!-- Desplegable de clientes -->
      
      <div class="collapse" id="clientes-collapse">
        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
          {% if perms.taller.view_cliente %}
          <li>
            <a href="{% url 'listarClientes' %}" class="link-dark rounded"
              >Listado de clientes</a
            >
          </li>
          {% endif %}
        </ul>
      </div>
      
    </li>
    {% endif %}
  </ul>
</div>

TallerChaPin/templates/sidebar_taller_home.html
<div class="flex-shrink-0 p-3 bg-white" style="width: 280px">
  <a
    href="/"
    class="
      d-flex
      align-items-center
      pb-3
      mb-3
      link-dark
      text-decoration-none
      border-bottom
    "
  >
    <svg class="bi me-2" width="30" height="24">
      <use xlink:href="#bootstrap"></use>
    </svg>
    <span class="fs-5 fw-semibold">Gestion de taller</span>
  </a>
  <ul class="list-unstyled ps-0">
    <ul class="list-unstyled ps-0">

      <!-- Clientes -->
      <li class="mb-1">
        {% if perms.taller.view_cliente %}
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse"
          data-bs-target="#clientes-collapse" aria-expanded="false">
          Clientes
        </button>
        
        <!-- Desplegable de clientes -->
        <div class="collapse" id="clientes-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            {% if perms.taller.view_cliente %}
            <li>
              <a href="{% url 'listarClientes' %}" class="link-dark rounded">Listado de clientes</a>
            </li>
            {% endif %}
          </ul>
        </div>
        {% endif %}
      </li>
    
    <!-- Vehículos -->
    <li class="mb-1">
      {% if perms.taller.view_vehiculo %}
      <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse"
        data-bs-target="#vehiculos-collapse" aria-expanded="false">
        Vehículos
      </button>

      <!-- Desplegable de vehículos -->
      <div class="collapse" id="vehiculos-collapse">
        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
        {% if perms.taller.view_vehiculo %}
          <li>
            <a href="{% url 'listarVehiculos' %}" class="link-dark rounded">Listar vehículos</a>
          </li>
        {% endif %}
        </ul>
      </div>
      {% endif %}
    </li>

    <!-- Tareas -->
    <li class="mb-1">
      {% if perms.taller.view_tarea %}
      <button
        class="btn btn-toggle align-items-center rounded collapsed"
        data-bs-toggle="collapse"
        data-bs-target="#tareas-collapse"
        aria-expanded="false"
      >
        Tareas
      </button>

      <!-- Desplegable de tareas -->
      <div class="collapse" id="tareas-collapse">
        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
          {% if perms.taller.add_tarea %}
          <li>
            <a href="{% url 'crearTarea' %}" class="link-dark rounded">Registrar una tarea</a>
          </li>
          {% endif %}
          {% if perms.taller.view_tarea %}
          <li>
            <a href="{% url 'listarTareas' %}" class="link-dark rounded">Listar tareas</a>
          </li>
          {% endif %}
          {% if perms.taller.add_tipotarea %}
          <li>
            <a href="{% url 'crearTipoTarea' %}" class="link-dark rounded">Registrar un tipo de tarea</a>
          </li>
          {% endif %}
          {% if perms.taller.view_tipotarea %}
          <li>
            <a href="{% url 'listarTipoTarea' %}" class="link-dark rounded">Listar tipos de tareas</a>
          </li>
          {% endif %}
        </ul>
      </div>
      {% endif %}
    </li>

    <!-- Materiales -->
    <li class="mb-1">
      {% if perms.taller.view_material %}
      <button
        class="btn btn-toggle align-items-center rounded collapsed"
        data-bs-toggle="collapse"
        data-bs-target="#materiales-collapse"
        aria-expanded="false"
      >
        Materiales
      </button>

      <!-- Desplegable de materiales -->
      <div class="collapse" id="materiales-collapse">
        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
          {% if perms.taller.add_tipomaterial %}
          <li>            
            <a href="{% url 'crearTipoMaterial' %}" class="link-dark rounded"
              >Registrar un tipo de material</a>
          </li>
          {% endif %}
          {% if perms.taller.view_tipomaterial %}
          <li>
            <a href="{% url 'listarTipoMateriales' %}" class="link-dark rounded"
              >Listar tipos de materiales</a>
          </li>
          {% endif %}
          {% if perms.taller.view_material %}
          <li>
            <a href="{% url 'listarMateriales' %}" class="link-dark rounded">Listar Materiales</a>
          </li>
          {% endif %}
        </ul>
      </div>
      {% endif %}
    </li>

    <!-- Repuestos -->
    <li class="mb-1">
      {% if perms.taller.view_repuesto %}
      <button
        class="btn btn-toggle align-items-center rounded collapsed"
        data-bs-toggle="collapse"
        data-bs-target="#repuestos-collapse"
        aria-expanded="false"
      >
        Repuestos
      </button>

      <!-- Desplegable de repuestos -->
      <div class="collapse" id="repuestos-collapse">
        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
          {% if perms.taller.view_repuesto %}
          <li>
            <a href="{% url 'listarRepuestos' %}" class="link-dark rounded">Listar repuestos</a>
          </li>
          {% endif %}
        </ul>
      </div>
      {% endif %}
    </li>

   <!-- Empleados -->
   <li class="mb-1">
    {% if perms.taller.view_empleado %}
    <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse"
      data-bs-target="#empleados-collapse" aria-expanded="false">
      Empleados
    </button>

    <!-- Desplegable de empleados -->
    <div class="collapse" id="empleados-collapse">
      <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
        {% if perms.taller.view_empleado %}
        <li>
          <a href="{% url 'listarEmpleados' %}" class="link-dark rounded">
            Lista de empleados</a>
        </li>
        {% endif %}
      </ul>
    </div>
    {% endif %}
    </li>

    <!-- Modelos -->
    <li class="mb-1">
      {% if perms.taller.view_modelo %}
      <button
        class="btn btn-toggle align-items-center rounded collapsed"
        data-bs-toggle="collapse"
        data-bs-target="#modelos-collapse"
        aria-expanded="false"
      >
        Modelos
      </button>

      <!-- Desplegable de modelos -->
      <div class="collapse" id="modelos-collapse">
        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
          {% if perms.taller.add_modelo %}
          <li>
            <a href="{% url 'crearModelo' %}" class="link-dark rounded"
              >Registrar un modelo</a
            >
          </li>
          {% endif %}
          {% if perms.taller.view_modelo %}
          <li>
            <a href="{% url 'listarModelos' %}" class="link-dark rounded"
              >Listar modelos</a
            >
          </li>
          {% endif %}
        </ul>
      </div>
      {% endif %}
    </li>

    <!-- Marcas -->
    <li class="mb-1">
      {% if perms.taller.view_marca %}
      <button
        class="btn btn-toggle align-items-center rounded collapsed"
        data-bs-toggle="collapse"
        data-bs-target="#marcas-collapse"
        aria-expanded="false"
      >
        Marcas
      </button>

      <!-- Desplegable de marcas -->
      <div class="collapse" id="marcas-collapse">
        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
          {% if perms.taller.add_marca %}
          <li>
            <a href="{% url 'crearMarca' %}" class="link-dark rounded"
              >Registrar una marca</a
            >
          </li>
          {% endif %}
          {% if perms.taller.view_marca %}
          <li>
            <a href="{% url 'listarMarcas' %}" class="link-dark rounded"
              >Listar marcas</a
            >
          </li>
          {% endif %}
        </ul>
      </div>
    </li>
    {% endif %}
  </ul>
</div>